version: '3'
services:
        oracledb:
                image: epiclabs/docker-oracle-xe-11g
                environment:
                        - ORACLE_ALLOW_REMOTE=true
                        - RELAX_SECURITY=1
                expose:
                        - 1521
                ports:
                        - "1521:1521"
              
        sigi_base:
                depends_on:
                        - oracledb
                image: ramonfdlr/sigiweb:2
                expose:
                        - 80
                ports:
                        - "80:80"
                links:
                        - oracledb
